name: Code Quality Checks

on: [push, pull_request]

jobs:
  python-checks:
    name: Python Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 src/steam_shortcut_manager.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/steam_shortcut_manager.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check formatting with black
        run: |
          black --check src/steam_shortcut_manager.py

      - name: Type check with mypy
        run: |
          mypy src/steam_shortcut_manager.py --ignore-missing-imports

  flatpak-checks:
    name: Flatpak Manifest and AppData
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder libxml2-utils

      - name: Basic Manifest Sanity Check (JSON validation)
        run: |
          MANIFEST_FILE="io.github.liberavia.steamshortcutmanager.json"
          echo "Validating JSON structure of ${MANIFEST_FILE}..."
          if [ ! -f "${MANIFEST_FILE}" ]; then
            echo "ERROR: Manifest file ${MANIFEST_FILE} not found at the repository root!"
            exit 1
          fi
          python3 -m json.tool "${MANIFEST_FILE}" > /dev/null
          if [ $? -ne 0 ]; then
            echo "JSON validation failed for ${MANIFEST_FILE}!"
            exit 1
          fi
          echo "JSON structure for ${MANIFEST_FILE} appears valid."

      - name: Validate AppData XML
        run: |
          APPDATA_FILE="appdata/io.github.liberavia.steamshortcutmanager.appdata.xml"
          echo "Validating AppData XML structure of ${APPDATA_FILE}..."
          if [ ! -f "${APPDATA_FILE}" ]; then
            echo "ERROR: AppData file ${APPDATA_FILE} not found!"
            exit 1
          fi
          xmllint --noout "${APPDATA_FILE}"
