name: Code Quality Checks

on: [push, pull_request]

jobs:
  python-checks:
    name: Python Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 src/steam_shortcut_manager.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 src/steam_shortcut_manager.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check formatting with black
        run: |
          black --check src/steam_shortcut_manager.py

      - name: Type check with mypy
        run: |
          # Ensure Pillow and python-vdf are in requirements.txt and installed for mypy.
          mypy src/steam_shortcut_manager.py --ignore-missing-imports

  flatpak-checks:
    name: Flatpak Manifest and AppData
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder libxml2-utils # libxml2-utils for xmllint

      - name: Basic Manifest Sanity Check (JSON validation)
        run: |
          # A simple check to see if the JSON is well-formed.
          echo "Validating JSON structure of io.github.liberavia.steamshortcutmanager.json..."
          python3 -m json.tool io.github.liberavia.steamshortcutmanager.json > /dev/null
          if [ $? -ne 0 ]; then
            echo "JSON validation failed for io.github.liberavia.steamshortcutmanager.json!"
            exit 1
          fi
          echo "JSON structure for io.github.liberavia.steamshortcutmanager.json appears valid."

      - name: Validate AppData XML
        run: |
          xmllint --noout appdata/io.github.liberavia.steamshortcutmanager.appdata.xml
